Phoenix.VLE.Web/ViewModels/GalleryViewModel.cs
using Phoenix.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Phoenix.VLE.Web.ViewModels
{
    public class GalleryViewModel
    {
        public List<GalleryFile> GalleryFolders { get; set; }
        public List<GalleryFile> GalleryFiles { get; set; }
        public List<int> GalleryFilesItemCount { get; set; }
    }
}

Phoenix.VLE.Web/Areas/Events/Controllers/SchoolEventsController.cs
using Phoenix.Common;
using Phoenix.Common.Helpers;
using Phoenix.Common.Models;
using Phoenix.VLE.Web.Helpers;
using Phoenix.VLE.Web.Models;
using Phoenix.VLE.Web.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Phoenix.VLE.Web.Areas.Events.Controllers
{
    public class SchoolEventsController : Controller
    {

        // GET: Events/SchoolEvents
        public ActionResult Index()
        {
            LoadDropdowns();
            return View();
        }
        [HttpPost]
        public ActionResult SaveSchoolEvent(SchoolEventEdit schoolEventEdit)
        {
            
            HttpPostedFileBase file = Session["resourceFile"] as HttpPostedFileBase;
            //File Upload
            if (file != null)
            {
                string strFile = (file.FileName).Replace(" ", String.Empty).Replace("(", String.Empty).Replace(")", String.Empty);
                string basePath = Constants.SchoolEventUploads;
                if (!Directory.Exists(basePath))
                    Directory.CreateDirectory(Constants.SchoolEventUploads);
                file.SaveAs(Server.MapPath(Constants.SchoolEventUploads + strFile));
                schoolEventEdit.ResourceFile = strFile;
            }


            //
            schoolEventEdit.SchoolId = SessionHelper.CurrentSession.SchoolId;
            schoolEventEdit.UserId = SessionHelper.CurrentSession.Id;
            schoolEventEdit.CreatedBy = SessionHelper.CurrentSession.Id;
            schoolEventEdit.UpdatedBy = SessionHelper.CurrentSession.Id;
            //schoolEventEdit.EventTypeId = "1";//School Event
            IEventService _eventService = new EventService();
            var result = _eventService.EventCUD(schoolEventEdit);
            return Json(new OperationDetails(result), JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public void SaveResourceFile(SchoolEventEdit schoolEventEdit)
        {
            Session["resourceFile"] = schoolEventEdit.ResourceFileUploade;
        }

        public ActionResult Detail(int id)
        {
            LoadDropdowns();
            IEventService _eventService = new EventService();
            SchoolEventEdit model = _eventService.GetSchoolEvent(id).FirstOrDefault();
            return View(model);
        }

        private void LoadDropdowns()
        {
            IDurationService _durationService = new DurationService();
            ViewBag.DurationList = _durationService.GetDuration(0);
            IEventCategoryService _eventCategoryService = new EventCategoryService();
            ViewBag.EventCategoryList = _eventCategoryService.GetEventCategory(0);
        }

        public ActionResult Update(int id)
        {
            LoadDropdowns();
            IEventService _eventService = new EventService();
            SchoolEventEdit model = _eventService.GetSchoolEvent(id).FirstOrDefault();
            return View(model);
        }
    }
}

Phoenix.VLE.Web/Areas/SchoolStructure/Controllers/SchoolSpacesController.cs
using Phoenix.Common;
using Phoenix.Common.Helpers;
using Phoenix.Common.Localization;
using Phoenix.Common.Logger;
using Phoenix.Common.ViewModels;
using Phoenix.Models;
using Phoenix.Models.Entities;
using Phoenix.VLE.Web.EditModels;
using Phoenix.VLE.Web.Services;
using Phoenix.VLE.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Newtonsoft.Json;
using Phoenix.VLE.Web.Models.EditModels;

namespace Phoenix.VLE.Web.Areas.SchoolStructure.Controllers
{
    public class SchoolSpacesController : BaseController
    {
        private readonly ISchoolSpaceService _schoolSpaceService;
        private readonly ITeacherDashboardService _teacherDashboardService;
        private readonly IStudentService _studentService;
        private readonly IUserService _userService;
      //  private readonly ILeaveService _leaveService;
        //private readonly IFeePaymentsService _feePaymentService;
        //private readonly ICalendarService _calendarService;
        //private readonly IEventCategoryService _eventCategoryService;
        private readonly IFileService _fileService;
        private List<VLEFileType> _fileTypeList;
        List<GalleryFile> galleryFiles = new List<GalleryFile>();
        private ILoggerClient _loggerClient;

        public SchoolSpacesController(ITeacherDashboardService teacherDashboardService
            , ISchoolSpaceService schoolSpaceService
            , IStudentService studentService, IUserService userService
            //, IEventCategoryService eventCategoryService
            //, ILeaveService leaveService
            , IFileService fileService
            //, IFeePaymentsService feePaymentService
            //, ICalendarService calendarService
            )
        {
            _teacherDashboardService = teacherDashboardService;
            _schoolSpaceService = schoolSpaceService;
            _studentService = studentService;
            _userService = userService;
            //_eventCategoryService = eventCategoryService;
           // _leaveService = leaveService;
            _fileService = fileService;
            _fileTypeList = _fileService.GetFileTypes().ToList();
            //_feePaymentService = feePaymentService;
            //_calendarService = calendarService;
        }
        // GET: Users/SchoolSpaces

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetFilteredCirculars(string fromDate, string toDate, int pageIndex = 1)
        {
            int skipCount = (pageIndex - 1) * 20;
            var model = new Pagination<Circular>();
            var circulars = GetCircularList(fromDate, toDate);
            if (circulars.Any())
            {
                var circularsShown = circulars.Count > skipCount ? circulars.Skip(skipCount).Take(20) : new List<Circular>();
                model = new Pagination<Circular>(pageIndex, 20, circularsShown.ToList(), circulars.Count);
            }
            model.LoadPageRecordsUrl = "/SchoolStructure/SchoolSpaces/GetFilteredCirculars?pageIndex={0}&fromDate=" + fromDate + "&toDate=" + toDate;
            model.SearchString = string.Empty;
            model.PageIndex = pageIndex;
            return PartialView("_CircularGrid", model);
        }

        public List<Circular> GetCircularList(string fromDate, string toDate)
        {
            string userId = "", key = "";
            List<Circular> circulars = new List<Circular>();
            _loggerClient = LoggerClient.Instance;
            try
            {
                if (SessionHelper.CurrentSession.IsParent())
                {
                    userId = SessionHelper.CurrentSession.UserName;
                    key = "Parent";
                }
                else if (SessionHelper.CurrentSession.IsTeacher() || SessionHelper.CurrentSession.IsAdmin)
                {
                    userId = SessionHelper.CurrentSession.UserName;
                    key = "Staff";
                }
                else if (SessionHelper.CurrentSession.IsStudent())
                {
                    userId = SessionHelper.CurrentSession.OldUserId.ToString();
                    key = "Student";
                }

                //circulars = _calendarService.GetCircularList(userId, key, "", fromDate, toDate, "");

                if (circulars == null)
                {
                    circulars = new List<Circular>();
                }

            }
            catch (Exception ex)
            {
                _loggerClient.LogException(ex);
            }
            return circulars;
        }

        public ActionResult CircularsNewsletters()
        {
            return View();
        }
        public JsonResult ShowPopupDetail(int circularId)
        {
            Circular circular = new Circular();
            //circular = _calendarService.GetCircularDetails(Convert.ToString(circularId), "en");
            return Json(circular, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult UpdateNewsletterIsRead(string circularData)
        {

            string userId = "", key = " ";
            if (SessionHelper.CurrentSession.IsParent())
            {
                userId = SessionHelper.CurrentSession.UserName;
                key = "Parent";
            }
            else if (SessionHelper.CurrentSession.IsTeacher() || SessionHelper.CurrentSession.IsAdmin)
            {
                userId = SessionHelper.CurrentSession.UserName;
                key = "Staff";
            }
            else if (SessionHelper.CurrentSession.IsStudent())
            {
                userId = SessionHelper.CurrentSession.OldUserId.ToString();
                key = "Student";
            }
            circularData = circularData.Replace("{0}", key).Replace("{1}", userId);
            bool result = false;// _calendarService.updateCircularDetails(circularData);
            return Json(new OperationDetails(result), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ResourceCategories()
        {
            List<ResourceCategory> categories = new List<ResourceCategory>();
            List<Resource> resources = new List<Resource>();
            _loggerClient = LoggerClient.Instance;

            try
            {
                string parentId = "", teacherId = "", isStaff = "";
                if (SessionHelper.CurrentSession.IsParent())
                {
                    parentId = SessionHelper.CurrentSession.UserName;
                    isStaff = "0";
                }
                else if (SessionHelper.CurrentSession.IsTeacher() || SessionHelper.CurrentSession.IsAdmin)
                {
                    teacherId = SessionHelper.CurrentSession.UserName;
                    isStaff = "1";
                }
                else
                {
                    parentId = _userService.GetUserById(SessionHelper.CurrentSession.ParentId).UserName;
                    isStaff = "0";
                }
                //if (SessionHelper.CurrentSession.IsParent() || SessionHelper.CurrentSession.IsTeacher() || SessionHelper.CurrentSession.IsAdmin || SessionHelper.CurrentSession.IsStudent())
                    //categories = _calendarService.GetResourceCategories(parentId, "en", isStaff, teacherId);

                if (categories == null)
                {
                    categories = new List<ResourceCategory>();
                }
                categories = categories.Where(c => c.schoolID == SessionHelper.CurrentSession.SchoolId.ToString()).ToList();

                if (categories.Count > 0 && categories[0].resourcesCategories != null && categories[0].resourcesCategories.Count > 0)
                {
                    for (int i = 0; i < categories[0].resourcesCategories.Count; i++)// foreach (var cat in categories[0].resourcesCategories)
                    {
                        //get resources for specific category
                        //resources = _calendarService.GetResources(parentId, SessionHelper.CurrentSession.SchoolId.ToString(), categories[0].resourcesCategories[i].categoryID.ToString(), "", "en", isStaff, teacherId);
                        for (int j = 0; j < resources.Count; j++)
                        {
                            if (categories[0].resourcesCategories[i].resources == null)
                            {
                                categories[0].resourcesCategories[i].resources = new List<Resource>();
                            }
                            var fileExt = Path.GetExtension(resources[j].resourceAttachmentUrl).Replace(".", "");
                            resources[j].FileIcon = _fileTypeList.Where(e => e.Extension == fileExt).FirstOrDefault().Icon;
                            categories[0].resourcesCategories[i].resources.Add(resources[j]);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                _loggerClient.LogException(ex);
            }
            return View(categories);
        }
        public ActionResult Resources(string id)
        {
            List<Resource> resources = new List<Resource>();
            _loggerClient = LoggerClient.Instance;
            try
            {
                string parentId = "", teacherId = "", isStaff = "";
                if (SessionHelper.CurrentSession.IsParent())
                {
                    parentId = SessionHelper.CurrentSession.UserName;
                    isStaff = "0";
                }
                else if (SessionHelper.CurrentSession.IsTeacher() || SessionHelper.CurrentSession.IsAdmin)
                {
                    teacherId = SessionHelper.CurrentSession.UserName;
                    isStaff = "1";
                }

Phoenix.VLE.Web/Areas/SchoolStructure/Views/SchoolSpaces/CircularsNewsletters.cshtml
@using Phoenix.Common.Localization
@{
    ViewBag.Title = "My Community";
    ViewBag.headerIcon = "ic-groups title-icon";
    ViewData["PageIcon"] = Url.Content("~/content/vle/img/svg/ic-schoolspaces.svg");
    ViewData["MyCommunity"] = "CircularNewsletter";
    var currentDate = DateTime.Now;
    var firstDay = new DateTime(currentDate.Year, currentDate.Month, 1);
    var lastDate = firstDay.AddMonths(1).AddDays(-1);
}

<style>
    .newsletter-circular-table .unread-row {
        background-color: #fff;
        border: 1px solid #cecece;
    }
    .newsletter-circular-table .read-row .table-text{
        font-weight:normal;
    }
</style>
<div class="row pb-4">
    @Html.Partial("_SchoolSpacesPartial")
</div>
<div class="row">
    <div class="col-lg-12 col-md-12 col-12">
        <div class="community-search d-flex justify-content-end row search-row">
            <div class="col-12 col-lg-5 col-md-3 col-sm-6 col-xl-4 col-xs-11">
                <div class="search-with-bg border">
                    <span class="icon-search"></span>
                    <input type="search" class="searchfield" id="search-cricular" placeholder="@ResourceManager.GetString("SchoolGroup.SchoolGroup.SearchGroup")">
                </div>
            </div>
            <div class="col-xl-2 col-lg-4 col-md-3 col-sm-6 col-xs-12 col-12">
                <div class="md-form md-outline sort-dropdown mb-1 mb-sm-0">
                    <label class="select-label">@ResourceManager.GetString("Shared.Labels.Show")</label>
                    <select class="selectpicker"  id="ddlCirularNewsletterType">
                        <option value="ALL" selected>@ResourceManager.GetString("Shared.Labels.All")</option>
                        <option value="CIRCULAR">@ResourceManager.GetString("Shared.Labels.Circular")</option>
                        <option value="NEWSLETTER">@ResourceManager.GetString("Shared.Labels.NewsLetter")</option>
                    </select>
                </div>
            </div>
            <div class="col-xl-2 col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="md-form md-outline date-time-picker field-with-icon bg-white mb-1 mb-sm-0">
                    <i class="far fa-calendar-alt active"></i>
                    <input type="text" class="form-control date-picker datepicker fromdate" placeholder="@ResourceManager.GetString("Shared.Labels.FromDate")" value="@firstDay.ToString("dd-MMM-yyyy")" id="fromDate">
                  
                </div>
            </div>
            <div class="col-xl-2 col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="md-form md-outline date-time-picker field-with-icon bg-white">
                    <i class="far fa-calendar-alt active"></i>
                    <input type="text" class="form-control date-picker datepicker todate" placeholder="@ResourceManager.GetString("Shared.Labels.ToDate")" value="@lastDate.ToString("dd-MMM-yyyy")" id="toDate">
                   
                </div>
            </div>
        </div>
        <!-- search section end -->
        <!-- teacher grid card -->
        <div class="row grid-view">
            <div class="col-lg-12 col-md-12 col-12">
                <div class="card community-wrapper">
                    <div class="responsive-list-table pagination-panel table-responsive" id="divCircularGrid">
                        @*@Html.Partial("_CircularGrid", Model)*@
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- modal popups -->
<div class="modal fade" id="selectCircularModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="circularModalTitle">@ResourceManager.GetString("School.SchoolSpace.CircularNewsletters")</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col flex" id="circularModalTitle">

                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col flex" id="divEmailDetails">

                    </div>
                </div>
                <div class="row">
                    <br />
                    <div class="col-lg-12 col-md-12 col flex" id="divEmailAttachments">
                      
                    </div>
                </div>
                <div class="row">
                    <div class="attachment-date ml-2" id="divdate">
                        <input type="text" id="SetDate" data-date-format='dd-MMM-yyyy' name="fname" style="outline:none;border:none">
                        @*<input type=text data-date-format='yy-mm-dd' id="SetDate">*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- modal popups end -->

@section pageplugins{
    @Html.Partial("_DataPageLibrariesPartial")
}
@section scripts
{
    <script>
        translatedResources.noRecordsMessage = ' @string.Format(ResourceManager.GetString("School.SchoolSpace.NoDataDisplayMessage"), ResourceManager.GetString("School.SchoolSpace.CircularNewsletters").ToLower())';
    </script>

    <script src="@Url.Content("~/Content/js/custom/SchoolSpaces/CircularsNewsletters.js?v="+@ResourceManager.GetString("Shared.Version.Js"))"></script>
}

Phoenix.VLE.Web/Areas/SchoolStructure/Views/SchoolSpaces/StudentSpacesIndex.cshtml
@model IEnumerable<Phoenix.Models.SchoolSpace>
@using Phoenix.Common.Helpers
@using Phoenix.Common.Localization
@using Phoenix.Common.ViewModels
@{
    ViewBag.Title = "My Community";
    ViewData["PageIcon"] = Url.Content("~/content/vle/img/svg/ic-schoolspaces.svg");

    var pageHeader = ResourceManager.GetString("School.SchoolSpace.SchoolSpacePageHeader");
    var searchClass = "page-search";
    var rnd = DateTime.Now.Ticks.ToString();
}
<div class="row">
    @Html.Partial("_SchoolSpacesPartial")
</div>
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-12">
        <div class="card min-height">
            <div class="card-body">
                <!-- user groups content start -->
                <div class="my-community column-padding pt-3 pb-3">

                </div>
                <!-- user groups content end -->
            </div>
        </div>
    </div>
</div>
@section pageplugins{
    @Html.Partial("_DataPageLibrariesPartial")
}
@section scripts
{
    <script src="@Url.Content("~/Content/js/custom/SchoolInfo/Studentspaces.js?v="+@ResourceManager.GetString("Shared.Version.Js"))"></script>
}

Phoenix.VLE.Web/Areas/SchoolStructure/Views/SchoolSpaces/_LeaveApplicationModal.cshtml
@model Phoenix.Models.Entities.LeaveRequest
@using Phoenix.Common.Localization
@using Phoenix.Common.Helpers
@using Phoenix.Common.Helpers.Extensions
@using Phoenix.Common.Enums
@{
    var LstLeaveReason = ViewBag.LeaveReasonList;
    var FileExtension = ViewBag.FileExtension;
    var IsAddViewEdit = ViewBag.IsAddViewEdit;
    var selectText = ResourceManager.GetString("Shared.Labels.Select");
    var showUpl = (Model.Attachment_FILE_NAME != null && Model.Attachment_FILE_NAME != "") || (ViewBag.IsAddViewEdit == "view") ? "d-none" : "";
}

@using (Ajax.BeginForm("SaveLeaveApplication", "SchoolSpaces", new AjaxOptions { OnSuccess = "addEditLeaveRequest.onSaveLeaveSuccess('" + Model.IsAddMode + "')", OnBegin = "addEditLeaveRequest.saveLeaveRequest()", OnFailure = "addEditLeaveRequest.onSaveLeaveError('" + Model.IsAddMode + "')" }, new { id = "frmAddEditLeaveRequest", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(d => d.StudentNo);
    @Html.HiddenFor(d => d.Leave_Type);
    @Html.HiddenFor(d => d.Enable_Button);
    @Html.HiddenFor(d => d.Ref_Id)
    @Html.HiddenFor(d => d.IsAddMode)
    @Html.HiddenFor(d => d.UploadedImageName)
    @Html.HiddenFor(d => d.ActualImageName)
    <div class="modal-header">
        <h5 class="modal-title" id="eventTitle">Leave Note </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="popup-form">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12">
                    <div class="card">
                        <div class="card-body pt-3 pb-3">
                            <div class="row column-padding">
                                <div class="col-lg-6 col-md-6 col-12">
                                    <div class="date-time-picker md-form md-outline">
                                        @Html.TextBoxFor(x => x.From_Date, "{0:dd-MMM-yyyy}",
                                       new { @class = "form-control date-picker date-picker1", onkeydown = "return false", onpaste = "return false", @type = "text", @data_maxdateid = "To_Date" })
                                        @Html.LocalizedLabel("active", "LeaveRequest.Leave.StartDate")
                                        @Html.ValidationMessageFor(x => x.From_Date)
                                    </div>

                                </div>
                                <div class="col-lg-6 col-md-6 col-12">
                                    <div class="date-time-picker md-form md-outline">
                                        @Html.TextBoxFor(x => x.To_Date, "{0:dd-MMM-yyyy}", new { onkeydown = "return false", onpaste = "return false", @class = "form-control date-picker date-picker2", @type = "text", @data_mindateid = "From_Date" })
                                        @Html.LocalizedLabel("active", "LeaveRequest.Leave.EndDate")
                                        @Html.ValidationMessageFor(x => x.To_Date)
                                    </div>

                                </div>
                            </div>
                            <div class="row column-padding">
                                <div class="col-lg-12 col-md-12 col-12">
                                    <div class="md-form md-outline">
                                        @Html.DropDownListFor(x => x.LeaveReasonId, new SelectList(LstLeaveReason, "Id", "Descr"), selectText, new { @class = "selectpicker" })
                                        @Html.LocalizedLabel("active", "LeaveRequest.Leave.ddlLeaveTypes")
                                        @Html.ValidationMessageFor(x => x.LeaveReasonId)
                                    </div>

                                </div>
                            </div>
                            <div class="row column-padding">
                                <div class="col-lg-12 col-md-12 col-12">
                                    <div class="md-form md-outline">
                                        @Html.TextAreaFor(x => x.Remarks, new { @class = "md-textarea form-control", id = "txtRemarks" })
                                        @Html.LocalizedLabel("active", "LeaveRequest.Leave.Remark")
                                        @Html.ValidationMessageFor(x => x.Remarks)
                                    </div>
                                </div>
                            </div>
                            <div class="row column-padding">
                                @if ((ViewBag.IsAddViewEdit == "edit" || ViewBag.IsAddViewEdit == "view") && Model.Attachment_FILE_NAME != null && Model.Attachment_FILE_NAME != "")
                                {
                                    <div id="library" class="">
                                        <div class="library-content clearfix">
                                            <div class="item-icon">
                                                <a id="ViewFile" data-assignmentId="@Model.Ref_Id" data-id="@EncryptDecryptHelper.EncryptUrl(Model.Ref_Id)" data-fileName="@EncryptDecryptHelper.EncryptUrl(Model.Attachment_FILE_NAME)">
                                                    @if (Model.Attachment_FILE_NAME.ToLower().Contains(".pdf"))
                                                    {
                                                        <i class="fas fa-file-pdf ic-file-pdf">
                                                        </i>
                                                    }
                                                    else if (Model.Attachment_FILE_NAME.ToLower().Contains(".xls") || Model.Attachment_FILE_NAME.Contains(".xlsx"))
                                                    {
                                                        <i class="fas fa-file-excel ic-file-excel"></i>
                                                    }
                                                    else if (Model.Attachment_FILE_NAME.ToLower().Contains(".doc") || Model.Attachment_FILE_NAME.Contains(".docx"))
                                                    {
                                                        <i class="fas fa-file-word ic-file-word"></i>
                                                    }
                                                    @*else if (Model.Attachment_FILE_NAME.ToLower().Contains(".jpg") || Model.Attachment_FILE_NAME.Contains(".png") || Model.Attachment_FILE_NAME.Contains(".bmp"))
                                                        {
                                                            <i class="fas fa-file-image ic-file-img"></i>
                                                        }*@
                                                    else if (Model.Attachment_FILE_NAME.ToLower().Contains(".ppt"))
                                                    {
                                                        <i class="fas fa-file-powerpoint ic-file-ppt"></i>
                                                    }
                                                    else
                                                    {
                                                        <i class="fas fa-file-alt ic-file"> </i>
                                                    }

                                                </a>
                                            </div>
                                            <div class="caption">
                                                <p>@Model.Attachment_FILE_NAME</p>
                                                <div class="quick-nav dropleft">
                                                    <button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                                                        <i class="fas fa-ellipsis-v"></i>
                                                        <span class="sr-only">@ResourceManager.GetString("Shared.Labels.ToggleDD")</span>
                                                    </button>
                                                    <div class="dropdown-menu z-depth-1">
                                                        <a class="dropdown-item" href="@Model.Attachment_URL" target="_blank">@ResourceManager.GetString("Shared.Buttons.Download")</a>
                                                        @if (ViewBag.IsAddViewEdit == "edit")
                                                        {
                                                            <a class="dropdown-item" id="ahrefDeleteFiles" data-assignmentId="@Model.Ref_Id" data-fileName="@Model.Attachment_FILE_NAME">@ResourceManager.GetString("Shared.Buttons.Delete")</a>
                                                        }

                                                        @*<a class="dropdown-item" id="ViewFile" data-assignmentId="@Model.Ref_Id" data-fileName="@EncryptDecryptHelper.EncryptUrl(Model.Attachment_FILE_NAME)">@ResourceManager.GetString("Shared.Buttons.View")</a>*@
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }

                                <div id="imgUpload" class="@showUpl">
                                    <div class="col-lg-12 col-md-12 col-12">
                                        <div class="md-form md-outline">
                                            <div class="standalone-uploader">
                                                <input id="dropAreaLeave" name="LeaveFile" type="file">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- file upload drawer end -->
            <div class="col-lg-12 col-md-12 col">
                <div class="md-form md-outline">
                    @Html.TextBoxFor(d => d.ActualImageName, new { @class = "form-control d-none" })
                    @Html.ValidationMessageFor(x => x.ActualImageName)
                </div>
            </div>
        </div>
    </div>
    if (ViewBag.IsAddViewEdit != "view")
    {
        <div class="modal-footer">
            <div class="d-flex justify-content-end">
                <button type="button" class="btn btn-outline-primary waves-effect waves-light" data-dismiss="modal">@ResourceManager.GetString("Shared.Buttons.Cancel")</button>
                <button type="button" class="btn btn-primary waves-effect waves-light" onclick="addEditLeaveRequest.saveLeaveRequest();" id="btnSaveLeaveRequest">@ResourceManager.GetString("Shared.Buttons.Save")</button>
            </div>
        </div>
    }
}