Phoenix.VLE.Web/Areas/Document/Controllers/CertificateController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Phoenix.Common;
using Phoenix.Common.Enums;
using Phoenix.Common.Helpers;
using Phoenix.Common.Helpers.Extensions;
using Phoenix.Common.Localization;
using Phoenix.Models;
using Phoenix.VLE.Web.EditModels;
using Phoenix.VLE.Web.Helpers;
using Phoenix.VLE.Web.Services;
using Phoenix.VLE.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Phoenix.VLE.Web.Areas.Document.Controllers
{
    public class CertificateController : BaseController
    {

        private readonly IStudentCertificateService _studentCertificateService;
        private readonly IUserPermissionService _userPermissionService;
        private readonly ITemplateService _templateService;
        private readonly ISchoolGroupService _schoolGroupService;

        public CertificateController(IStudentCertificateService studentCertificateService, IUserPermissionService userPermissionService,
                ITemplateService templateService, ISchoolGroupService schoolGroupService)
        {
            _studentCertificateService = studentCertificateService;
            _userPermissionService = userPermissionService;
            _templateService = templateService;
            _schoolGroupService = schoolGroupService;
        }
        // GET: Document/Certificate
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadCertificateGrid()
        {
            var syncContext = SynchronizationContext.Current;
            SynchronizationContext.SetSynchronizationContext(null);
            var isCustomPermissionEnabled = _userPermissionService.IsCustomPermissionAssigned(Convert.ToInt32(SessionHelper.CurrentSession.Id), PermissionCodes.U_StudentCertificate.ToString()).Result;
            SynchronizationContext.SetSynchronizationContext(syncContext);

            IEnumerable<Template> templateList = new List<Template>();
            templateList = _templateService.GetTemplatesBySchoolId((int)SessionHelper.CurrentSession.SchoolId, Convert.ToInt32(SessionHelper.CurrentSession.Id), true, Enum.GetName(typeof(PlanTemplateTypes), PlanTemplateTypes.Certificate), null);
            var dataList = new
            {
                aaData = (from item in templateList
                          select new
                          {
                              item.Title,
                              item.Description,
                              item.TemplateType,
                              Status = ResourceManager.GetString("Template.Template." + Enum.GetName(typeof(TemplateStatus), item.TeacherApprovalStatus).Replace(" ", "")),
                              Actions = GetTemplateActionLinks(isCustomPermissionEnabled, item)
                          }).ToArray()
            };

            return Json(dataList, JsonRequestBehavior.AllowGet);
        }


        public ActionResult LoadSchoolGroups(int pageIndex = 1, string searchString = "", bool isBeSpokeGroup = false)
        {
            var model = new Pagination<Phoenix.Models.SchoolGroup>();
            var oldSearchString = searchString;
            searchString = searchString.Replace(" /", "_");
            if (SessionHelper.CurrentSession.IsTeacher() || SessionHelper.CurrentSession.IsAdmin)
            {
                var syncContext = SynchronizationContext.Current;
                SynchronizationContext.SetSynchronizationContext(null);
                var teacherGroups = _schoolGroupService.GetSchoolGroups(pageIndex, 6, (isBeSpokeGroup ? 1 : 0), searchString).Result.ToList();
                SynchronizationContext.SetSynchronizationContext(syncContext);

                if (teacherGroups.Any())
                    model = new Pagination<Phoenix.Models.SchoolGroup>(pageIndex, 6, teacherGroups, teacherGroups.FirstOrDefault().TotalCount);
                model.RecordCount = teacherGroups.Count == 0 ? 0 : teacherGroups[0].TotalCount;
            }
            model.LoadPageRecordsUrl = "/Document/Certificate/LoadSchoolGroups?pageIndex={0}&isBeSpokeGroup=" + isBeSpokeGroup;
            model.SearchString = oldSearchString;
            return PartialView("_TeacherSchoolGroups", model);
        }
        private string GetTemplateActionLinks(bool isPermissionEnabled, Template model)
        {
            string actions = string.Empty;
            actions +=  (model.CanApproveTemplate & model.IsStudentAssigned && model.StudentAssignedBy != SessionHelper.CurrentSession.Id ? $"<a class='mr-2' href='javascript:void(0)' data-toggle='tooltip'  data-original-title='" + ResourceManager.GetString("Template.Template.UpdateTemplateStatus") + $"' onclick='certificate.initTemplateStatusForm(this, {model.TemplateId})'><img src='/Content/vle/img/svg/pencil-big.svg' /></a>" : string.Empty)
               + (isPermissionEnabled && (SessionHelper.CurrentSession.IsTeacher() || SessionHelper.CurrentSession.IsAdmin) ? $"<a class='mr-2' href='javascript:void(0)' data-toggle='tooltip'  data-original-title='" + ResourceManager.GetString("Template.Template.AssignStudents") + $"' onclick='certificate.assignStudents(this, {model.TemplateId})'><img src='/Content/vle/img/svg/tbl-settings.svg' /></a>" : string.Empty)
                + $"<a class='mr-2' href='javascript:void(0)' data-toggle='tooltip' data-original-title='{ ResourceManager.GetString("Template.Template.PreviewCertificateTemplate")} ' onclick=certificate.previewCertificate(this) data-id='{EncryptDecryptHelper.EncryptUrl(model.TemplateId)}'><img src='/Content/vle/img/svg/tbl-view.svg'/></button>";
            return actions;
        }

        public ActionResult InitTemplateUpdateStatusForm(int templateId)
        {
            ViewBag.TemplateStatus = new List<Common.Models.ListItem>() {
                new Common.Models.ListItem{ ItemId = Convert.ToInt16(TemplateStatus.Pending).ToString(), ItemName = ResourceManager.GetString("Template.Template.Pending")},
                new Common.Models.ListItem{ ItemId = Convert.ToInt16(TemplateStatus.Approved).ToString(), ItemName = ResourceManager.GetString("Template.Template.Approved")},
                new Common.Models.ListItem{ ItemId = Convert.ToInt16(TemplateStatus.Rejected).ToString(), ItemName = ResourceManager.GetString("Template.Template.Rejected")}
            };
            var editModel = new TemplateEdit();
            var template = _templateService.GetTemplateDetail(templateId, (int)SessionHelper.CurrentSession.SchoolId, null, null, SessionHelper.CurrentSession.Id.ToInteger(), null, true);
            EntityMapper<Template, TemplateEdit>.Map(template, editModel);
            return PartialView("_FormTemplateStatus", editModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveTemplateCertificateStatus(TemplateEdit model)
        {
            var op = new OperationDetails();
            var template = _templateService.GetTemplateDetail(model.TemplateId.ToInteger(), (int)SessionHelper.CurrentSession.SchoolId, StringEnum.GetStringValue(PlanTemplateTypes.Certificate), null, SessionHelper.CurrentSession.Id.ToInteger(), null, true);
            bool canApproveTemplate = template.CanApproveTemplate;
            if (!(canApproveTemplate && template.StudentAssignedBy != SessionHelper.CurrentSession.Id && template.IsStudentAssigned))
            {
                op.Message = LocalizationHelper.ActionNotPermittedMessage;
                op.NotificationType = StringEnum.GetStringValue(NotificationTypeConstants.Warning);
                return Json(op, JsonRequestBehavior.AllowGet);
            }
            model.UpdatedBy = SessionHelper.CurrentSession.Id;
            bool result = _templateService.SaveTemplateCertificateStatus(model);
            return Json(new OperationDetails(result), JsonRequestBehavior.AllowGet);
        }

        public ActionResult AssignStudents(int templateId)
        {
            const int maxLength = 50;
            var schoolGroups = _schoolGroupService.GetSchoolGroupsByUserId(SessionHelper.CurrentSession.Id, true).ToList();
            ViewBag.SchoolGroups = schoolGroups.Select(i => new Phoenix.Common.Models.ListItem
            {
                ItemId = i.SchoolGroupId.ToString(),
                ItemName = !string.IsNullOrEmpty(i.TeacherGivenName) ? (i.TeacherGivenName.Length > maxLength ? i.TeacherGivenName.Substring(0, maxLength) + "..." : i.TeacherGivenName) : (i.SchoolGroupDescription.Length > maxLength ? i.SchoolGroupDescription.Substring(0, maxLength) + "..." : i.SchoolGroupDescription)
            });
            ViewBag.TemplateId = templateId;
            return PartialView("_CertificateStudentMapping");
        }

        public ActionResult GetTeacherGroups(int pageIndex = 1, string searchString = "")
        {
            int pageSize = 9;
            if (pageIndex == 0) pageIndex = 1;
            int skipItemsCount = (pageIndex - 1) * 9;
            var schoolGroups = _schoolGroupService.GetSchoolGroupsByUserId(SessionHelper.CurrentSession.Id, true).ToList();
            schoolGroups = schoolGroups.Where(e => e.SchoolGroupName.ToLower().Contains(searchString.ToLower())).ToList();
            var model = new Pagination<Phoenix.Models.SchoolGroup>();
            if (schoolGroups.Any())
                model = new Pagination<Phoenix.Models.SchoolGroup>(pageIndex, pageSize, schoolGroups.Skip(skipItemsCount).Take(9).ToList(), schoolGroups.Count);
            model.RecordCount = schoolGroups.Count == 0 ? 0 : schoolGroups[0].TotalCount;
            model.LoadPageRecordsUrl = "/Document/Certificate/GetTeacherGroups?pageIndex={0}&searchString=" + searchString;
            model.SearchString = searchString;
            return PartialView("_TeacherSchoolGroups", model);
        }

Phoenix.VLE.Web/Areas/StudentCertificates/Views/Certificate/AddEditCertificate.cshtml
@model Phoenix.VLE.Web.EditModels.CertificateEdit
@using Phoenix.Common.Localization
@using Phoenix.Common.Helpers.Extensions

@{
    var file = TempData["File"].ToString();
    //  string baseUrl ="http://localhost:9890/";
    var baseUrl = "http://localhost:9890/pixie/";
    var url = baseUrl + file;
    //var Sname = TempData["StudentName"];
    bool value = Convert.ToBoolean(Session["Role"]);


}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>Image Editor</title>

    <link href="~/pixie/styles.min.css?v20" rel="stylesheet" />
    @*<link rel="stylesheet" href="styles.min.css?v20">*@
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500' rel='stylesheet' type='text/css'>

    <link href="~/Content/StyleSheet1.css" rel="stylesheet" />
    <style>

        body, html {
            margin: 0;
            width: 100%;
            height: 100%;
        }
    </style>
</head>
<body>
    <div class="modal-body">
        <div class="popup-form">
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.CertificateId)


            @Html.HiddenFor(x => x.IsAddMode)
            <div class="row">
                <div class="col-lg-12 col-md-12 col">
                    <div class="md-form md-outline">
                        @Html.TextBoxFor(x => x.CertificateName, new { @class = "form-control" })
                        @Html.LocalizedLabel("active", "StudentInformation.Certificates.CertificateName")
                        @Html.ValidationMessageFor(x => x.CertificateName)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col">
                    <div class="md-form md-outline">
                        @Html.TextBoxFor(x => x.CertificateDescription, new { @class = "form-control" })
                        @Html.LocalizedLabel("active", "StudentInformation.Certificates.CertificateDescription")
                        @Html.ValidationMessageFor(x => x.CertificateDescription)
                    </div>
                </div>
            </div>



        </div>
    </div>

    <pixie-editor>
        <div class="global-spinner">
            <style>
                .global-spinner {
                    display: none;
                    align-items: center;
                    justify-content: center;
                    z-index: 999;
                    background: #fff;
                    position: fixed;
                    top: 0;
                    left: 0;
                    width: 100%;
                    height: 100%;
                }
            </style>

            <div class="la-ball-spin-clockwise la-2x">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
        <script>
            setTimeout(function () {
                var spinner = document.querySelector('.global-spinner');
                if (spinner) spinner.style.display = 'flex';
            }, 50);</script>
    </pixie-editor>
    @*<script src="scripts.min.js?v27"></script>*@
    <script src="~/Content/js/jquery-3.3.1.min.js?v="+@ResourceManager.GetString("Shared.Version.Js")></script>
    @*<script src="~/Scripts/jquery-3.3.1.min.js?v="+@ResourceManager.GetString("Shared.Version.Js")></script>
        <script src="~/pixie/scripts.min.js?v27"></script>*@
    <script src="~/pixie/scripts.min.v1.js?v27"></script>
    <script>
        var currentdate = new Date();
        var pixie = new Pixie({
            ui: {
                visible: true,

                theme: 'light',
                allowEditorClose: false,
                allowZoom: true,
                toolbar: {
                    hideSaveButton: false,
                    hide: @value.ToString().ToLower(),
                    hideOpenButton: true,
                    hideCloseButton: true,
                },
                nav: {
                    position: 'none',
                    replaceDefault: true,
                },
            },

            // ENTER CONFIGURATION HERE
            baseUrl: '@baseUrl',
            onLoad: function () {

                var activeObject = pixie.get('activeObject');
                //activeObject.setValues({
                //    backgroundColor: 'blue',
                //    opacity: 0.5
                //});
                console.log(activeObject.canvasState.fabric._iTextInstances[0].text);

              //  activeObject.canvasState.fabric._iTextInstances[0].text = "";
                //pixie.http().post('file:///D:/codecanyon-iVGKX38f-pixie-image-editor/pixie/', { state: state });
                //pixie.loadStateFromUrl('file:///C:/Users/Neosoft/Downloads/pixie/pixie/certificate.json').then(function () {
                //    //state has been loaded
                //});
            },
            onSave: function (data, name) {

                console.log(JSON.stringify(data));
                alert(JSON.stringify(data));
                pixie.http().post('/Demo/Save/', { name: name, data: data }).subscribe(function (response) {
                })
            },
            image:'@url',
            tools: {
                export: {
                    defaultFormat: 'json', //png, jpeg or json
                    defaultName: "image" + currentdate.getDate() +
                        + (currentdate.getMonth() + 1) +
                        + currentdate.getFullYear() +
                        + currentdate.getHours() +
                        + currentdate.getMinutes() +
                        + currentdate.getSeconds(), //default name for downloaded photo file
                    defaultQuality: 0.8, //works with jpeg only, 0 to 1
                }
            }
        });
    </script>
    <script>
        @Html.Partial("_ValidationJSPartial")

    </script>
</body>
</html>

Phoenix.VLE.Web/Areas/StudentCertificates/Views/Certificate/Index.cshtml
@model IEnumerable<Phoenix.VLE.Web.EditModels.CertificateEdit>
@using Phoenix.Common.Localization
@using Phoenix.Common.Helpers.Extensions
@using Phoenix.Common.Helpers

@{
    ViewBag.Title = ResourceManager.GetString("StudentInformation.Certificates.Certificates");
    ViewData["PageIcon"] = Url.Content("~/content/vle/img/svg/ic-quiz.svg");
    var rnd = DateTime.Now.Ticks.ToString();
    var admin = SessionHelper.CurrentSession.IsAdmin;
}



<div class="row">
    <div class="col-lg-12 col-md-12 col-12">
        <div class="card">
            <div class="card-body column-padding pt-3 pb-3" id="card_body">

                <div class="row">
                    @Html.AntiForgeryToken()
                    <div class="col-lg-8 col-md-8 col-8">
                        <div class="search-with-bg">
                            <i class="fa fa-search"></i>
                            <input type="search" id="QuizListSearch" class="searchfield" placeholder="Search" />
                        </div>
                    </div>
                    @if (ViewBag.IsCustomPermission && !admin)
                    {
                        <div class="col-lg-4 col-md-4 col-4">
                            <div class="float-right">
                                <button onclick="window.location.href='/StudentCertificates/Certificate/AddEditCertificate'" class="btn btn-primary btn-sm m-0">@ResourceManager.GetString("Assignment.Assignment.ArchiveAssignment")<i class="fas fa-eye ml-2"></i></button>
                                @*<button id="btnAddQuiz" type="button" class="btn btn-primary waves-effect waves-light">@ResourceManager.GetString("Quiz.Quiz.AddQuiz")</button>*@
                            </div>
                        </div>
                    }
                    
                </div>
                <div class="table-wrapper mt-2">
                    <table class="table table-bordered table-hover table-responsive-md" id="tbl-Quiz"></table>
                </div>
            </div>

        </div>
    </div>
</div>



@section pageplugins{
    @Html.Partial("_DataPageLibrariesPartial")
}
@section scripts
{
    <script language="javascript">
        translatedResources.CertificateName= '@ResourceManager.GetString("StudentInformation.Certificates.CertificateName")';
        translatedResources.CertificateDescription = '@ResourceManager.GetString("StudentInformation.Certificates.CertificateDescription")';
        translatedResources.CertificateId= '@ResourceManager.GetString("StudentInformation.Certificates.CertificateId")';

        @*translatedResources.QuizTaskEditValidationMessage= '@ResourceManager.GetString("Quiz.Quiz.QuizTaskEditValidationMessage")';
        translatedResources.QuizTaskDeleteValidationMessage= '@ResourceManager.GetString("Quiz.Quiz.QuizTaskDeleteValidationMessage")';
        translatedResources.DeletedSuccessfully= '@ResourceManager.GetString("Quiz.Quiz.DeletedSuccessfully")';*@
    </script>
    <script src="@Url.Content("~/Content/js/addons/jquery.minicolors.min.js?v="+@ResourceManager.GetString("Shared.Version.Js"))"></script>
    <script src="@Url.Content("~/Content/js/custom/StudentInformation/Certificate.js?v="+@ResourceManager.GetString("Shared.Version.Js"))"></script>
}

Phoenix.VLE.Web/Areas/StudentCertificates/Views/Certificate/_AddEditCerificate.cshtml
@model Phoenix.VLE.Web.EditModels.CertificateEdit
@using Phoenix.Common.Localization
@using Phoenix.Common.Helpers.Extensions
@using Phoenix.Common
@{

  
    // var expectedDate = Model.ExpectedDate != null ? Model.ExpectedDate : DateTime.Now;
}

@using (Ajax.BeginForm("SaveCertificateData", "Certificate", new AjaxOptions { OnSuccess = "quiz.onSaveSuccess" }, new { id = "frmAddCycle", @class = "form-horizontal" }))
{
    <div class="modal-body">
        <div class="popup-form">
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.CertificateId)


            @Html.HiddenFor(x => x.IsAddMode)
            <div class="row">
                <div class="col-lg-12 col-md-12 col">
                    <div class="md-form md-outline">
                        @Html.TextBoxFor(x => x.CertificateName, new { @class = "form-control" })
                        @Html.LocalizedLabel("active", "StudentInformation.Certificates.CertificateName")
                        @Html.ValidationMessageFor(x => x.CertificateName)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col">
                    <div class="md-form md-outline">
                        @Html.TextBoxFor(x => x.CertificateDescription, new { @class = "form-control" })
                        @Html.LocalizedLabel("active", "StudentInformation.Certificates.CertificateDescription")
                        @Html.ValidationMessageFor(x => x.CertificateDescription)
                    </div>
                </div>
            </div>



        </div>
    </div>
    <div class="modal-footer">
        <div class="d-flex justify-content-end">
            <button type="button" class="btn btn-outline-primary waves-effect waves-light" data-dismiss="modal">@ResourceManager.GetString("Shared.Buttons.Cancel")</button>
            @if (Html.CurrentPagePermission().CanEdit)
            {
                <button type="submit" class="btn btn-primary waves-effect waves-light">@ResourceManager.GetString("Shared.Buttons.Save")</button>
            }
            
        </div>
    </div>
}

@Html.Partial("_ValidationJSPartial")

Phoenix.VLE.Web/Areas/StudentCertificates/Views/Certificate/_AddEditCertificatePartial.cshtml
@model Phoenix.VLE.Web.EditModels.CertificateEdit
@using Phoenix.Common.Localization
@using Phoenix.Common.Helpers.Extensions

@{
    var file = TempData["File"].ToString();
    //  string baseUrl ="http://localhost:9890/";
    var baseUrl = "http://localhost:9890/pixie/";
    var url = baseUrl + file;
 
    bool value = Convert.ToBoolean(Session["Role"]);
    int Count = Model.count;

}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>Image Editor</title>

    <link href="~/pixie/styles.min.css?v20" rel="stylesheet" />
    @*<link rel="stylesheet" href="styles.min.css?v20">*@
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500' rel='stylesheet' type='text/css'>

    <link href="~/Content/StyleSheet1.css" rel="stylesheet" />
    <style>

        body, html {
            margin: 0;
            width: 100%;
            height: 100%;
        }
    </style>
</head>
<body>
    @using (Ajax.BeginForm("SaveCertificateData", "Certificate", new AjaxOptions { OnSuccess = "quiz.onSaveSuccess" }, new { id = "frmAddCycle", @class = "form-horizontal" }))
    {
        <div class="modal-body">
            <div class="popup-form">
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.CertificateId)
                @Html.HiddenFor(x => x.FieldValue)


                @Html.HiddenFor(x => x.IsAddMode)
                <div class="row">
                    <div class="col-lg-12 col-md-12 col">
                        <div class="md-form md-outline">
                            @Html.TextBoxFor(x => x.CertificateName, new { @class = "form-control" })
                            @Html.LocalizedLabel("active", "StudentInformation.Certificates.CertificateName")
                            @Html.ValidationMessageFor(x => x.CertificateName)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col">
                        <div class="md-form md-outline">
                            @Html.TextBoxFor(x => x.CertificateDescription, new { @class = "form-control" })
                            @Html.LocalizedLabel("active", "StudentInformation.Certificates.CertificateDescription")
                            @Html.ValidationMessageFor(x => x.CertificateDescription)
                        </div>
                    </div>
                </div>



            </div>
        </div>
        <div class="modal-footer">
            <div class="d-flex justify-content-end">
                <button type="button" class="btn btn-outline-primary waves-effect waves-light" data-dismiss="modal">@ResourceManager.GetString("Shared.Buttons.Cancel")</button>
                @if (Html.CurrentPagePermission().CanEdit)
                {
                    <button type="submit" class="btn btn-primary waves-effect waves-light">@ResourceManager.GetString("Shared.Buttons.Save")</button>
                }

            </div>
        </div>
    }

    <pixie-editor>
        <div class="global-spinner">
            <style>
                .global-spinner {
                    display: none;
                    align-items: center;
                    justify-content: center;
                    z-index: 999;
                    background: #fff;
                    position: fixed;
                    top: 0;
                    left: 0;
                    width: 100%;
                    height: 100%;
                }
            </style>

            <div class="la-ball-spin-clockwise la-2x">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
        <script>
            setTimeout(function () {
                var spinner = document.querySelector('.global-spinner');
                if (spinner) spinner.style.display = 'flex';
            }, 50);</script>
    </pixie-editor>
    @*<script src="scripts.min.js?v27"></script>*@
    <script src="~/pixie/scripts.min.v1.js?v27"></script>
    @*<script src="~/Content/js/jquery-3.3.1.min.js?v="+@ResourceManager.GetString("Shared.Version.Js")></script>*@

    
    <script>
        var currentdate = new Date();
        var pixie = new Pixie({
            ui: {
                visible: true,

                theme: 'light',
                allowEditorClose: false,
                allowZoom: true,
                toolbar: {
                    hideSaveButton: false,
                    hide: @value.ToString().ToLower(),
                    hideOpenButton: false,
                    hideCloseButton: false,
                },

            },

            // ENTER CONFIGURATION HERE
            baseUrl: '@baseUrl',
            onLoad: function () {

                var activeObject = pixie.get('activeObject');
                //activeObject.setValues({
                //    backgroundColor: 'blue',
                //    opacity: 0.5
                //});
                console.log(activeObject.canvasState.fabric._iTextInstances[0].text);

            },
            onSave: function (data, name) {
                debugger
                var values = $('#FieldValue').val();
                var activeObject = pixie.get('activeObject');
                var count = activeObject.canvasState.fabric._iTextInstances.length;
             
                if (@Count == count) {
                    for (var i = 0; i < @Count; i++) {
                        var str = values.split(',');
                        {
                            if (str[i] == activeObject.canvasState.fabric._iTextInstances[i].text) {
                                console.log(str[i], activeObject.canvasState.fabric._iTextInstances[i].text);
                                console.log(JSON.stringify(data));
                                //alert(JSON.stringify(data));
                                pixie.http().post('/StudentCertificates/Certificate/Save/', { name: name, data: data }).subscribe(function (response) {
                                })
                            }

                        }

                    };


                }
                else if (@Count > count || @Count<= 0) {
                    let remainingValue = [];
                    for (var i = 0; i < @Count; i++) {
                        var str = values.split(',');
                        {
                            if (activeObject.canvasState.fabric._iTextInstances[i]!=undefined && str[i] == activeObject.canvasState.fabric._iTextInstances[i].text) {
                                console.log(str[i], activeObject.canvasState.fabric._iTextInstances[i].text);
                                console.log(JSON.stringify(data));
                               
                            }
                            else
                            {
                                remainingValue.push(str[i])
                            }


                        }

                    };
                    globalFunctions.showMessage('Add Fields', remainingValue);
                    console.log(remainingValue);

                }
                else {
                    alert("Add remaining fields");
                }

            },
            image:'@url',
            tools: {
                export: {
                    defaultFormat: 'json', //png, jpeg or json
                    defaultName: "image" + currentdate.getDate() +
                        + (currentdate.getMonth() + 1) +
                        + currentdate.getFullYear() +
                        + currentdate.getHours() +
                        + currentdate.getMinutes() +
                        + currentdate.getSeconds(), //default name for downloaded photo file
                    defaultQuality: 0.8, //works with jpeg only, 0 to 1
                }
            }
        });
    </script>
   
</body>
</html>